Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\e00gs\.espressif\python_env\idf5.4_py3.13_env\Lib\site-packages\esptool\__main__.py", line 9, in <module>
    esptool._main()
    ~~~~~~~~~~~~~^^
  File "C:\Users\e00gs\.espressif\python_env\idf5.4_py3.13_env\Lib\site-packages\esptool\__init__.py", line 1314, in _main
    main()
    ~~~~^^
  File "C:\Users\e00gs\.espressif\python_env\idf5.4_py3.13_env\Lib\site-packages\esptool\__init__.py", line 1036, in main
    operation_func(esp, args)
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\e00gs\.espressif\python_env\idf5.4_py3.13_env\Lib\site-packages\esptool\cmds.py", line 491, in write_flash
    if set_flash_size and set_flash_size > flash_end:
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'int' and 'NoneType'
CMake Error at run_serial_tool.cmake:67 (message):
  
  C:/Users/e00gs/.espressif/python_env/idf5.4_py3.13_env/Scripts/python.exe;;D:/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32
  failed.



